//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempus.Utils.AspNetCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tempus.Utils.AspNetCore.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ já cadastrado.
        /// </summary>
        internal static string CnpjJaCadastrado {
            get {
                return ResourceManager.GetString("CnpjJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado.
        /// </summary>
        internal static string CpfJaCadastrado {
            get {
                return ResourceManager.GetString("CpfJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email inválido.
        /// </summary>
        internal static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente com este e-mail.
        /// </summary>
        internal static string EmailDuplicado {
            get {
                return ResourceManager.GetString("EmailDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrada.
        /// </summary>
        internal static string Entrada {
            get {
                return ResourceManager.GetString("Entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser igual a &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string equal_error {
            get {
                return ResourceManager.GetString("equal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro esta em uso.
        /// </summary>
        internal static string ErroAoExcluir {
            get {
                return ResourceManager.GetString("ErroAoExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar datas usando a expressão &apos;{0}&apos;, o termo &apos;{1}&apos; não foi reconhecido.
        /// </summary>
        internal static string ErroAoGerarDatasPelaExpressao {
            get {
                return ResourceManager.GetString("ErroAoGerarDatasPelaExpressao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro sofreu alteração por meio de outra rotina. Por favor, atualize a página e tente novamente.
        /// </summary>
        internal static string ErroDeConcorrencia {
            get {
                return ResourceManager.GetString("ErroDeConcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ter {MaxLength} caracteres, informados {TotalLength} caracteres.
        /// </summary>
        internal static string exact_length_error {
            get {
                return ResourceManager.GetString("exact_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve estar entre {From} e {To} (exclusivo).
        /// </summary>
        internal static string exclusivebetween_error {
            get {
                return ResourceManager.GetString("exclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser superior a &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string greaterthan_error {
            get {
                return ResourceManager.GetString("greaterthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser superior ou igual a &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string greaterthanorequal_error {
            get {
                return ResourceManager.GetString("greaterthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve estar entre {From} e {To}.
        /// </summary>
        internal static string inclusivebetween_error {
            get {
                return ResourceManager.GetString("inclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o endereço do cliente para entrega.
        /// </summary>
        internal static string InformeOEnderecoDoClienteParaEntrega {
            get {
                return ResourceManager.GetString("InformeOEnderecoDoClienteParaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ter {MinLength} a {MaxLength} caracteres. Introduziu {TotalLength} caracteres..
        /// </summary>
        internal static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser inferior a &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string lessthan_error {
            get {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser inferior ou igual a &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string lessthanorequal_error {
            get {
                return ResourceManager.GetString("lessthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível utilizar Cortesia com outras formas de recebimento.
        /// </summary>
        internal static string NaoPodeUsarCortesia {
            get {
                return ResourceManager.GetString("NaoPodeUsarCortesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível utilizar A receber com outras formas de recebimento.
        /// </summary>
        internal static string NaoPodeUsarReceber {
            get {
                return ResourceManager.GetString("NaoPodeUsarReceber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar pedido concluído ou unificado.
        /// </summary>
        internal static string NaoPossivelAlterarConcluidoOuUnificado {
            get {
                return ResourceManager.GetString("NaoPossivelAlterarConcluidoOuUnificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível unificar pedidos recebidos como cortesia.
        /// </summary>
        internal static string NaoPossivelUnificarPedidosCortesia {
            get {
                return ResourceManager.GetString("NaoPossivelUnificarPedidosCortesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um número de telefone ou o CPF.
        /// </summary>
        internal static string NomeDuplicado {
            get {
                return ResourceManager.GetString("NomeDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        internal static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser diferente de &apos;{ComparisonValue}&apos;.
        /// </summary>
        internal static string notequal_error {
            get {
                return ResourceManager.GetString("notequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        internal static string notnull_error {
            get {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido já registrado.
        /// </summary>
        internal static string PedidoJaCadastrado {
            get {
                return ResourceManager.GetString("PedidoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido.
        /// </summary>
        internal static string predicate_error {
            get {
                return ResourceManager.GetString("predicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido.
        /// </summary>
        internal static string regex_error {
            get {
                return ResourceManager.GetString("regex_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa deve possuir ao menos uma relação comercial.
        /// </summary>
        internal static string RelacaoComercial {
            get {
                return ResourceManager.GetString("RelacaoComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente é possível unificar pedidos abertos.
        /// </summary>
        internal static string SomentePermitidoUnificarPedidosAbertos {
            get {
                return ResourceManager.GetString("SomentePermitidoUnificarPedidosAbertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente com este telefone.
        /// </summary>
        internal static string TelefoneDuplicado {
            get {
                return ResourceManager.GetString("TelefoneDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O total dos recebimentos deve ser igual a {0}, mas o total atual é {1}.
        /// </summary>
        internal static string TotalDosRecebimentosInvalido {
            get {
                return ResourceManager.GetString("TotalDosRecebimentosInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor recebido deve ser igual ao valor da parcela.
        /// </summary>
        internal static string ValorRecebidoIgualValorParcela {
            get {
                return ResourceManager.GetString("ValorRecebidoIgualValorParcela", resourceCulture);
            }
        }
    }
}
